In [1]:
import numpy as np

In [2]:
my_array = np.array(["Emre","Tuana",3,46,True,0.78])

In [3]:
np.random.choice(my_array) #diziden rastgele eleman seçme

'46'

In [6]:
np.where(my_array) #elemanların indeksini döndürme

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [14]:
np.linspace(0,100) #belirtilen aralıkta eşit aralıklı sayılar üretir

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [29]:
my_secarray = np.random.randint(1,100,4) #belirtilen aralıkta belirtilen sayı kadar sayı üretme

In [30]:
my_secarray

array([97, 20, 42, 33])

In [31]:
np.min(my_secarray) #maximum ve minimum değerleri bulma
np.max(my_secarray)

97

In [33]:
sayilar = np.array([74,52,5465,123,65])

In [34]:
sayilar2 = np.array([34,96,7852,46,36])

In [38]:
sayilar3 = np.concatenate((sayilar,sayilar2)) #iki diziyi birleştirme

In [39]:
sayilar3

array([  74,   52, 5465,  123,   65,   34,   96, 7852,   46,   36])

In [42]:
np.split(sayilar3,5) #diziyi bölme

[array([74, 52]),
 array([5465,  123]),
 array([65, 34]),
 array([  96, 7852]),
 array([46, 36])]

In [43]:
np.std(sayilar3) #standart sapma hesaplama

2690.6984613664904

In [47]:
baska_sayilar = np.arange(0,100,2) #belirtilen aralıkta sayı dizisi oluşturma

In [48]:
baska_sayilar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [54]:
np.random.shuffle(baska_sayilar) #diziyi rastgele karıştırma

In [53]:
baska_sayilar

array([10, 14, 74, 68, 98, 56, 50, 24, 32, 30, 66, 96, 28,  2, 76, 72, 60,
       94,  0, 86, 88, 52, 84, 70, 48, 40, 62,  4, 90, 58, 22, 80, 12, 78,
       36,  8, 42, 38, 92, 18, 44, 20, 16, 54, 82, 34, 26,  6, 64, 46])